#version: "3.9"
#
#services:
#  postgres:
#    image: postgres:12
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "5433:5433"
#    volumes:
#      - data:/var/lib/postgresql/data
#
##  pg-admin:
##    image: dpage/pgadmin4:6
##    environment:
##      - PGADMIN_DEFAULT_EMAIL=admin@email.com
##      - PGADMIN_DEFAULT_PASSWORD=admin
##      - PGADMIN_LISTEN_PORT=5050
##
##    ports:
##      - "5050:5050"
#
#volumes:
#  data:



#services:
#  database:
#    image: postgres
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_USER: docker
#      POSTGRES_PASSWORD: docker
#      POSTGRES_DB: exampledb
#
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8080:8080

version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 2001:5432

volumes:
  postgresql_bin:
    driver: local
  postgresql_data:
    driver: local